baseURL = "/"
languageCode = "utf-8"
title = "Youchoose.ai"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
ourvision = false

[params]
   subtitle = "Youchoose"
   subsite = "youchoose"
   openGraphSiteName = "Youchoose"
   description = "Giving control back of YouTube recommendations to internet users. Users can decide to see the content recommendations from their favorite content creators."
   tagline = "YouChoose your recommendation system"
  # tagline = "Gain back control over your recommendations on YouTube"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug/"
  data = "/:filename/" # this isn't working - to do check

[menu]
 [[menu.main]]
    name = "Philosophy"
    url = "/philosophy/"
    weight = 10
 [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
 [[menu.main]]
    name = "🐣"
    url = "https://nitter.net/search?f=tweets&q=trackingexposed"
    weight = 30


 [[menu.featured]]
    name = "A browser extension to enhance your experience directly on YouTube"
    pre = "/images/community.jpeg"
    weight = 1
 [[menu.featured]]
    name = "Recommendations provided by the content creators"
#    url = "/users/1"
    pre = "/images/user.png"
    weight = 2
 [[menu.featured]]
    name= "Recommendation pointing to all the webside, not just YouTube"
#    name= "Recommend content from all around the web"
    pre = "/images/creators.png"
    weight = 3




 [[menu.footer]]
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    name = "Connected project: Algorithms Exposed"
    url = "https://algorithms.exposed"
    weight = 80
