baseURL = "/"
languageCode = "utf-8"
title = "Youchoose.ai"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
ourvision = false

[params]
   subtitle = "Youchoose"
   subsite = "youchoose"
   openGraphSiteName = "Youchoose"
   description = "Giving back control of YouTube recommendations to internet users. Users can decide to see the content recommendations from their favorite content creators."
   tagline = "Get back control over your recommendations on YouTube."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug/"
  data = "/:filename/" # this isn't working - to do check

[menu]
 [[menu.main]]
    name = "YT users"
    url = "/users/"
    weight = 20

 [[menu.main]]
    name = "YT content creators"
    url = "/creators/"
    weight = 10

    
 [[menu.main]]
    name = "YT community"
    url = "/turnesol/"
    weight = 0
    


# Homepage cards
# [[menu.featured]]
#    name = "I'm a user"
#    url = "/users/1"
#    pre = "/images/user.png"
#    post = "Find out how to get reccomendations selected by content creators"
#    weight = -30
#
# [[menu.featured]]
#    name= "I'm a content creator"
#    url = "creators"
#    pre = "/images/creators.png"
#    post = "Find out how to directly recommend videos to your audience"
#    weight = -20
#
# [[menu.featured]]
#    name = "I'm part of a community"
#    url = "/turnesol/"
#    pre = "/images/community.jpeg"
#    weight = -10
#    post = "Find out how to be part or create a community to mutually evalute videos and create community reccomandations"


 [[menu.featured]]
    name = "Get Recommendations from your Content Creators"
    url = "/users/1"
    pre = "/images/user.png"
    post = "Get recommendation from the content creator you are watching"
    weight = -30

 [[menu.featured]]
    name= "Participate to a Community of Content Curators"
    url = "creators"
    pre = "/images/creators.png"
    post = "Participate to a network of content curators, and see the best content recommended by your community."
    weight = -20

 [[menu.featured]]
    name = "Become a Data-Activist and Expose Shadow Banning! "
    url = "http://tournesol.app"
    pre = "/images/community.jpeg"
    weight = -10
    post = "Participate to a collective observation of algorithmic recommendations, to shed light on the YouTube algorithm and its hidden censorship patterns."



 [[menu.footer]]
    name = "Initial project analysis (2018)"
    url = "/initial-analysis/"
    weight = 100
 [[menu.footer]]
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    name = "Connected project: Algorithms Exposed"
    url = "https://algorithms.exposed"
    weight = 80
