baseURL = "/"
languageCode = "utf-8"
title = "Youchoose.ai"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
ourvision = false

[params]
   subtitle = "Youchoose"
   subsite = "youchoose"
   openGraphSiteName = "Youchoose"
   description = "Youtube content creator would be finally able to control their recommendation and don't see their content exploited by the surveillance capitalism"
   tagline = "Youtuber finally would control their recommendation, for better context and to don't let their watchers exploiter by click bait"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug/"
  data = "/:filename/" # this isn't working - to do check

[menu]
 [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0
 [[menu.main]]
    name = "Stats"
    url = "/impact/"
    weight = 10

 [[menu.main]]
    name = "More"
    url = "#"
    weight = 100
 [[menu.main]]
    parent = "More"
    name = "API Documentation"
    url = "/docs/"
    weight = 130
 [[menu.main]]
    name = "Contacts"
    parent = "More"
    url = "/about/"
    weight = 140
 [[menu.main]]
    name = "Automation"
    parent = "More"
    url = "/automation/"
    weight = 150
 [[menu.main]]
    name = "Privacy"
    parent = "More"
    url = "/privacy/"
    weight = 160
 [[menu.main]]
    parent = "More"
    name = "Youtuber Labor union"
    url = "/seeyou/"
    weight = 170

 [[menu.featured]]
    name = "Tutorial ― Learn how to use our tool"
    url = "/tutorial/1"
    pre = "/images/popup-opt-in.png"
    post = "Video and textual tutorial, on the basic usage, the evidence page, and everything a researcher need to start analyzing YT!"
    weight = -190
 [[menu.featured]]
    name= "No second box"
    url = "/wetest/announcement-1"
    pre = "/images/data.svg"
    post = "A collective observation of the Youtube personalization algorithm; addressing COVID-19 and getting evidence on how recommendations works"
    weight = -180
 [[menu.featured]]
    name = "CHIARO ― The Ranking Algorithm	"
    url = "/chiaro/start"
    pre = "/images/related.svg"
    weight = -170
    post = "Coordinated collection of yt search results; to spot tendencies, bubbles, and biases. real time psedonymized open data feed."



 [[menu.footer]]
    name = "Initial project analysis (2018)"
    url = "/initial-analysis/"
    weight = 100
 [[menu.footer]]
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    name = "Connected project: Algorithms Exposed"
    url = "https://algorithms.exposed"
    weight = 80
