# General Settings
title: "Youchoose"
email: "youchoose@tracking.exposed"
email_2: ""
description: >- # this means to ignore newlines until "baseurl:"
  Youchoose is an environment that allows you to experience a different recommendation system.
  What you need to see new content is a browser extension, available for Chrome and Firefox.
  Algorithms are opinionated too, especially when they try to boost ads revenues.

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"
light_logo_1x: "/assets/images/logo-light.png"
light_logo_2x: "/assets/images/logo-light@2x.png"

address_01: 
phone_number: 
copyright_text: "CC BY-NC 2.0 2021"
cookies: "we don't use cookies"

google_analytics:
  enable: false
  key: "UA-664136761-1"  # UA-664136761-1

social_accounts:
  title: "Social Media"
  links:
    - url: "https://twitter.com/YouChooseAI"
      icon: "jam jam-twitter"      
    - url: "https://www.youtube.com/channel/UCZQ6RK_b9grwh1V9zdo3exA"
      icon: "jam jam-youtube"

external_links:
  title: "Learn More"
  links:
    - url: "/about"
      text: "About Us"
    - url: "https://tracking.exposed/"
      text: "TrackingExposed"
    - url: "https://tracking.exposed/manifesto/"
      text: "Manifesto"


external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Our Team"
    - url: "#"
      text: "Strategy"
    - url: "#"
      text: "Service"
    - url: "#"
      text: "Mission"
    - url: "#"
      text: "Process"

footer_newsletter:
  title: "Our Newsbites"
  sub_title: "Subscribe to get sporadic news"
  subscribe_button_text: "Join"


one_page_nav_settings:
  links:
    - text: "Home"
      url: "#home"
    - text: "Services"
      url: "#services"
    - text: "Experiences"
      url: "#experiences"
    - text: "Portfolio"
      url: "#portfolio"
    - text: "Testimonials"
      url: "#testimonials"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg8.svg"

gallery:
  images:
  - img: "/assets/images/art/z7bn.png" #trex
    url: "https://tracking.exposed/"
  - img: "/assets/images/art/z9bn.png" #ledger
    url: "https://ledgerproject.eu/"
  - img: "/assets/images/art/z11bn.png" #eucommission
    url: "https://ec.europa.eu/info/index_en"
  - img: "/assets/images/art/z10bn.png" #hermes
    url: "https://www.hermescenter.org/"
  - img: "/assets/images/art/z12bn.png" #berkley
    url: "www.ischool.berkeley.edu"
  - img: "/assets/images/art/z13bn.png" #ovh
    url: "https://www.ovhcloud.com"
  - img: "/assets/images/art/z4bn.png" #blumorpho
    url: "https://blumorpho.org"
  - img: "/assets/images/art/z6bn.png" #ai forensics
    url: "https://www.aiforensics.org/"
  - img: "/assets/images/art/z15bn.png" #dyne
    url: "https://www.dyne.org/"
  - img: "/assets/images/art/z16bn.png" #cdm
    url: "https://competitivedigitalmarkets.eu/"